name: Pull Workflows from Template Repo

on:
  workflow_dispatch:
    inputs:
      version:
        desciption: "Version of the template-repo to pull (Tag or branch)"
        required: true
        default: 'main'  

permissions:                    # Global permissions configuration starts here
  contents: read                # 'read' access to repository contents
  pull-requests: write          # 'write' access to pull requests

jobs:
  pull-workflows:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.MY_PAT }}

      - name: Fetch deploy-dev-weblogic.yaml (if it exists)
        run: |
          curl -o .github/workflows/deploy-dev-weblogic.yaml https://raw.githubusercontent.com/Ravicharan-nettyam/template-repo/${{ github.event.inputs.version }}/.github/workflows/deploy-dev-weblogic.yml || echo "deploy-dev-weblogic.yaml does not exist in template-repo"
          curl -o .github/workflows/build-workflow.yaml https://raw.githubusercontent.com/Ravicharan-nettyam/template-repo/${{ github.event.inputs.version }}/.github/workflows/build-workflow.yml


      - name: Checking Contents
        run: |
          echo "Moving Files to .github"
          cd .github/workflows
          pwd
          ls
          

      - name: Commit and push the workflows
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "ravicharan.nettyam@telus.com"
          git config --global user.name "Ravicharan-nettyam"
          git add .
          # git add build-workflow.yaml || echo "No files to add"
          # git add deploy-dev-weblogic.yaml || echo "No deploy-dev-weblogic.yaml to add"
          git commit -m "Pulled workflows from template-repo (version: ${{ github.event.inputs.version }})" 
          # git push https://x-access-token:${{ env.PAT }}@github.com/Ravicharan-nettyam/code-repo.git main
          # git push --set-upstream origin main
          git push origin main



      # - name: Fetch build-workflow.yaml
      #   env: 
      #      GITHUB_TOKEN: ${{ github.token }}
      #   run: |
      #     curl -o build-workflow.yaml https://raw.githubusercontent.com/Ravicharan-nettyam/template-repo/${{ github.event.inputs.version }}/.github/workflows/build-workflow.yml
      #     mv build-workflow.yaml .github/workflows/
      #     git config --global user.email "ravicharan.nettyam@telus.com"
      #     git config --global user.name "Ravicharan-nettyam"
      #     git add .
      #     git commit -m "pushing"
      #      git push --set-upstream origin main

     