name: Pull Workflows from Template Repo

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the template-repo to pull (Tag or branch)"
        required: true
        default: 'main'
      components:
        description: "Components to pull (build, deploy-dev-weblogic, or both)"
        required: true
        default: 'both'
        type: choice
        options:
          - build
          - deploy-dev-weblogic
          - both

jobs:
  pull-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code-repo
        uses: actions/checkout@v3

      - name: Pull and Commit Workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch workflows from template-repo based on inputs
          if [[ "${{ github.event.inputs.components }}" == "build" || "${{ github.event.inputs.components }}" == "both" ]]; then
            curl -o .github/workflows/build-workflow.yaml https://raw.githubusercontent.com/Ravicharan-nettyam/template-repo/${{ github.event.inputs.version }}/.github/workflows/build-workflow.yaml
          fi
          if [[ "${{ github.event.inputs.components }}" == "deploy-dev-weblogic" || "${{ github.event.inputs.components }}" == "both" ]]; then
            curl -o .github/workflows/deploy-dev-weblogic.yaml https://raw.githubusercontent.com/Ravicharan-nettyam/template-repo/${{ github.event.inputs.version }}/.github/workflows/deploy-dev-weblogic.yaml
          fi

          # Check contents
          echo "Checking contents"
          ls .github/workflows

          # Commit and push the workflows
          git config --global user.email "kumarivijaya1125@gmail.com"
          git config --global user.name "aadi-1125"
          git add .github/workflows
          git commit -m "Pulled workflows from template-repo (version: ${{ github.event.inputs.version }})"
          git push origin main
